-- This file should undo anything in `up.sql`
ALTER TABLE data_entries
    DROP value_fragment_0_string,
    DROP value_fragment_0_integer,
    DROP value_fragment_1_string,
    DROP value_fragment_1_integer,
    DROP value_fragment_2_string,
    DROP value_fragment_2_integer,
    DROP value_fragment_3_string,
    DROP value_fragment_3_integer,
    DROP value_fragment_4_string,
    DROP value_fragment_4_integer,
    DROP value_fragment_5_string,
    DROP value_fragment_5_integer,
    DROP value_fragment_6_string,
    DROP value_fragment_6_integer,
    DROP value_fragment_7_string,
    DROP value_fragment_7_integer,
    DROP value_fragment_8_string,
    DROP value_fragment_8_integer,
    DROP value_fragment_9_string,
    DROP value_fragment_9_integer,
    DROP value_fragment_10_string,
    DROP value_fragment_10_integer;