[package]
name = "state-daemon"
version = "0.1.0"
authors = ["–êleksej Petrov <apetrov@web3tech.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4" }
envy = "0.4"
tonic = "0.2"
tokio = { version = "0.2", features = ["full"] }
waves-protobuf-schemas = { git = "https://github.com/wavesplatform/protobuf-schemas", branch = "blockchain-updates-from-1.2.6" }
slog = "2.5"
slog-term = "2.6"
slog-async = "2.5"
slog-json = "2.3"
async-trait = "0.1"
once_cell = "1.4"
bs58 = "0.3"
diesel = { version = "1.4.5", features = ["postgres", "chrono", "numeric"] }
num-traits = "0.2.2"
base64 = "0.12"
itertools = "0.9"

[[bin]]
name = "service"
path = "src/main.rs"
