CREATE TABLE IF NOT EXISTS blocks_microblocks (
	uid BIGINT GENERATED BY DEFAULT AS IDENTITY
		CONSTRAINT blocks_microblocks_uid_key
			UNIQUE,
	id VARCHAR NOT NULL
		CONSTRAINT blocks_microblocks_pkey
			PRIMARY KEY,
	height INTEGER NOT NULL,
	time_stamp BIGINT
);

CREATE INDEX IF NOT EXISTS blocks_microblocks_id_idx
	ON blocks_microblocks (id);

CREATE INDEX IF NOT EXISTS blocks_microblocks_time_stamp_uid_idx
	ON blocks_microblocks (time_stamp DESC, uid DESC);

CREATE TABLE IF NOT EXISTS data_entries (
    block_uid BIGINT NOT NULL
		CONSTRAINT data_entries_block_uid_fkey
			REFERENCES blocks_microblocks (uid)
				ON DELETE CASCADE,
	uid BIGINT GENERATED BY DEFAULT AS IDENTITY
		CONSTRAINT data_entries_uid_key
			UNIQUE,
	superseded_by BIGINT NOT NULL,
    address VARCHAR NOT NULL,
    key VARCHAR NOT NULL,
    transaction_id VARCHAR,
    value_binary TEXT,
    value_bool BOOLEAN,
    value_integer BIGINT,
    value_string VARCHAR,
    fragment_0_string VARCHAR,
    fragment_0_integer BIGINT,
    fragment_1_string VARCHAR,
    fragment_1_integer BIGINT,
    fragment_2_string VARCHAR,
    fragment_2_integer BIGINT,
    fragment_3_string VARCHAR,
    fragment_3_integer BIGINT,
    fragment_4_string VARCHAR,
    fragment_4_integer BIGINT,
    fragment_5_string VARCHAR,
    fragment_5_integer BIGINT,
    fragment_6_string VARCHAR,
    fragment_6_integer BIGINT,
    fragment_7_string VARCHAR,
    fragment_7_integer BIGINT,
    fragment_8_string VARCHAR,
    fragment_8_integer BIGINT,
    fragment_9_string VARCHAR,
    fragment_9_integer BIGINT,
    fragment_10_string VARCHAR,
    fragment_10_integer BIGINT,
	CONSTRAINT data_entries_pkey
		PRIMARY KEY (superseded_by, address, key)
);

CREATE INDEX IF NOT EXISTS data_entries_block_uid_idx
	ON data_entries (block_uid);

CREATE INDEX data_entries_fragment_0_string_idx ON data_entries (fragment_0_string);
CREATE INDEX data_entries_fragment_0_integer_idx ON data_entries (fragment_0_integer);
CREATE INDEX data_entries_fragment_1_string_idx ON data_entries (fragment_1_string);
CREATE INDEX data_entries_fragment_1_integer_idx ON data_entries (fragment_1_integer);
CREATE INDEX data_entries_fragment_2_string_idx ON data_entries (fragment_2_string);
CREATE INDEX data_entries_fragment_2_integer_idx ON data_entries (fragment_2_integer);
CREATE INDEX data_entries_fragment_3_string_idx ON data_entries (fragment_3_string);
CREATE INDEX data_entries_fragment_3_integer_idx ON data_entries (fragment_3_integer);
CREATE INDEX data_entries_fragment_4_string_idx ON data_entries (fragment_4_string);
CREATE INDEX data_entries_fragment_4_integer_idx ON data_entries (fragment_4_integer);
CREATE INDEX data_entries_fragment_5_string_idx ON data_entries (fragment_5_string);
CREATE INDEX data_entries_fragment_5_integer_idx ON data_entries (fragment_5_integer);
CREATE INDEX data_entries_fragment_6_string_idx ON data_entries (fragment_6_string);
CREATE INDEX data_entries_fragment_6_integer_idx ON data_entries (fragment_6_integer);
CREATE INDEX data_entries_fragment_7_string_idx ON data_entries (fragment_7_string);
CREATE INDEX data_entries_fragment_7_integer_idx ON data_entries (fragment_7_integer);
CREATE INDEX data_entries_fragment_8_string_idx ON data_entries (fragment_8_string);
CREATE INDEX data_entries_fragment_8_integer_idx ON data_entries (fragment_8_integer);
CREATE INDEX data_entries_fragment_9_string_idx ON data_entries (fragment_9_string);
CREATE INDEX data_entries_fragment_9_integer_idx ON data_entries (fragment_9_integer);
CREATE INDEX data_entries_fragment_10_string_idx ON data_entries (fragment_10_string);
CREATE INDEX data_entries_fragment_10_integer_idx ON data_entries (fragment_10_integer);
CREATE INDEX data_entries_key_idx ON data_entries(key);
CREATE INDEX data_entries_value_integer_idx ON data_entries(value_integer);
CREATE INDEX data_entries_value_string_idx ON data_entries(value_string);
